<?php

$plugin = array(
  'title' => t('State Library WW1 - 2 Column Layout'),
  'category' => t('State Library WW1'),
  'icon' => 'slnswww1-2col.png',
  'theme' => 'slnswww1-2col',
  'css' => 'slnswww1-2col.css',
  'regions' => array(
    'header' => t('Header'),
    'title-strip' => t('Title Strip'),
    'main' => t('Main'),
    'side' => t('Side'),
    'contact-strip' => t('Contact Strip'),
    'footer' => t('Footer')
  ),
);
