<?php
$plugin = array(
  'title' => t('State Library WW1 - Home Layout'),
  'category' => t('State Library WW1'),
  'icon' => 'slnswww1-home.png',
  'theme' => 'slnswww1-home',
  'css' => 'slnswww1-home.css',
  'regions' => array(
    'header' => t('Header'),
    'top-col-one'=> t('Top Col One'),
    'top-col-two'=> t('Top Col Two'),
    'top-col-three'=> t('Top Col Three'),
    'main' => t('Main'),
    'footer' => t('Footer')
  ),
);
