<?php
$plugin = array(
  'title' => t('State Library WW1 - Home Layout'),
  'category' => t('State Library WW1'),
  'icon' => 'slnswww1-home.png',
  'theme' => 'slnswww1-home',
  'css' => 'slnswww1-home.css',
  'regions' => array(
    'page-menu' => t('Page Menu'),
    'feature-video' => t('Feature Video'),
    'header' => t('Header'),
    'main' => t('Main'),
    'contact-strip-col-1' => t('Contact Strip Col 1'),
    'contact-strip-col-2' => t('Contact Strip Col 2'),
    'footer' => t('Footer')
  ),
);
